name: chapter03

on:
    pull_request:
        branches:
            - main

jobs:
    chapter03:
        runs-on: ubuntu-latest
        steps:
            - name: プルリクエストの情報を表示
              run: |
                echo "プルリクエストのブランチ名： ${{ github.head_ref }}"
                echo "プルリクエストの番号： ${{ github.event.pull_request.number }}"
                echo "プルリクエストの作成者： ${{ github.event.pull_request.user.login }}"
            - uses: actions/checkout@v4
              id: checkout # ステップID
            - name: actions/checkoutのステータスを表示
              # actions/checkout@v4が成功している場合はsuccessが表示される
              run: echo "${{ steps.checkout.conclusion }}"

    build:
        runs-on: ubuntu-latest
        steps:
            - name: outputディレクトリを作成
              run: mkdir output
            - name: ビルド処理（ダミー）
              run: touch output/artifact.zip


