name: chapter03

on:
    pull_request:
        branches:
            - main

jobs:
    chapter03:
        runs-on: ubuntu-latest
        steps:
            - name: プルリクエストの情報を表示
              run: |
                echo "プルリクエストのブランチ名： ${{ github.head_ref }}"
                echo "プルリクエストの番号： ${{ github.event.pull_request.number }}"
                echo "プルリクエストの作成者： ${{ github.event.pull_request.user.login }}"
